language: swift

matrix:
  include:
    - xcode_workspace: acmepos/AcmePos.xcworkspace
      xcode_scheme: AcmePos
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 8

    - xcode_workspace: kebabpos/KebabPos.xcworkspace
      xcode_scheme: KebabPos
      xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone 8
